import typography from "@tailwindcss/typography";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./app/**/*.php",
    "./vendor/filament/**/*.blade.php",
  ],
  safelist: [
    "adh-header-theme",
    "adh-tone-national",
    "adh-tone-commemoration",
    "adh-tone-bayram",
    "decor-soft",
    "decor-medium",
    "decor-strong",
    "adh-event-strip__identity",
    "adh-event-strip__badge",
    "adh-event-strip__label",
    "adh-event-strip__message",
    "adh-event-seal",
    "adh-event-seal__accent",
    "adh-event-seal--flag",
    "adh-event-seal--children",
    "adh-event-seal--portrait",
    "adh-event-seal--youth",
    "adh-event-seal--victory",
    "adh-event-seal--republic",
    "adh-event-seal--remembrance",
    "adh-event-seal--crescent",
    "adh-event-seal--ramazan",
    "adh-event-seal--kurban",
    "adh-event-badge__img",
    "adh-event-badge__img--flag",
    "adh-event-badge__img--portrait",
    "adh-event-badge__img--mono",
    "adh-event-badge__img--crescent",
    "adh-event-badge__mark",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        adh: {
          navy: "#1A1A2E",
          blue: "#16213E",
          red: "#C62828",
          "red-light": "#EF9A9A",
          bg: "#FAFAFA",
          text: "#212121",
          gray: "#757575",
          "gray-light": "#F5F5F5",
          border: "#E0E0E0",
        },
      },
      fontFamily: {
        serif: ["Lora", "Georgia", "serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [typography],
};
